name: ci/cd for deployment
run-name: ${{ github.actor }} is tigger ci/cd action

on: [push]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to github pages
        run: npm run deploy
