name: ci/cd for deployment
run-name: ${{ github.actor }} is tigger ci/cd action

on: [push]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo code
        uses: actions/checkout@v4
      - name: set node version
        uses: actions/setup-node@v4
        with:
          node-version: "14.18.1"
      - name: install dependencies
        run: npm install
      - name: upload build
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy to github pages
        uses: actions/deploy-pages@v4
